services:
  app:
    container_name: debian
    build:
      dockerfile: ./Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - db
    volumes:
      - ./www/:/var/www/html/
      
  db:
    container_name: mariadb
    image: mariadb:10.3.35
    # image: mariadb:10.5
    ports:
      - '3306:3306'
    volumes:
      - mySQLVolume:/var/lib/mysql
    env_file:
      - app/db.env
    command: 
      - --max_allowed_packet=128M
      # - --optimizer_switch=rowid_filter=OFF # Only for MariaDB 10.5
      # - --query_cache_size=16777216 # Only for MariaDB 10.5
      # - --query_cache_type=1 # Only for MariaDB 10.5
      # - --query_cache_limit=16777216 # Only for MariaDB 10.5
     
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

  phpadmin:
    container_name: phpadmin
    image: kwajahussain/phpadmin
    ports:
      - '80:80'
    depends_on:
      - db

volumes:
  mySQLVolume:
    external: true


