services:
  app:
    container_name: redcap-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REDCAP_VERSION: ${REDCAP_VERSION}
    ports:
      - '${REDCAP_HTTP_PORT:-8080}:80'
      - '${REDCAP_HTTPS_PORT:-8443}:443'
      - '${MYSQL_PORT:-3400}:3306'
      - '${MAILHOG_SMTP_PORT:-1025}:1025'
      - '${MAILHOG_UI_PORT:-8025}:8025'
      - '${PHPMYADMIN_PORT:-8081}:8081'
    environment:
      - REDCAP_VERSION=${REDCAP_VERSION}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-redcap}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - REDCAP_SALT=${REDCAP_SALT:-12345678}
      - REDCAP_HTTPS_PORT=${REDCAP_HTTPS_PORT:-8443}
    volumes:
      - ./mycert.crt:/etc/ssl/certs/mycert.crt:ro
      - ./mycert.key:/etc/ssl/private/mycert.key:ro
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
